### ISSUE TITLE
Some bounding box missing

### ISSUE THREAD

**Issue by legnaro** [shayanalibhatti/Retail-Store-Item-Detection-using-YOLOv5#3]
Hello Shayan,

Thanks for sharing this amazing project.

I realized that are missing some box in this image, how can I improve the accuracy in this case? (img attached)

![img_1](https://user-images.githubusercontent.com/7379954/120131935-cbe9f380-c19f-11eb-9ab6-a9a1fcf09f85.jpg)
![result](https://user-images.githubusercontent.com/7379954/120132022-f89e0b00-c19f-11eb-9f16-8b31928d1da4.jpg)

**Comment by shayanalibhatti** [comment]
Thanks for liking. If you used my model, then it was only trained on 1000 images out of 10000
images i think, that SKU dataset had. If you can train on more images that
would be great and you will see good and considerable improvement in
accuracy.

For any project if you want to improve accuracy, use your own model never
the pretrained model specially if you are building a commercial product and
train on as much images as you can,  otherwise augment the images you have
if the original ones arent too many.

Hope that helps.

**Comment by legnaro** [comment]
Tks for the quick answer, I will try to train my own model :-)
